spring:
  application:
    name : Shopping-Service

  jpa:
    show-sql: true
    database:
      platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/shopping_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8081

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true