spring:
  application:
    name : Shopping-Service

  config:
    import: optional:configserver:http://localhost:8085


  datasource:
    url: jdbc:mysql://localhost:3306/shopping_service
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8081