spring:
  application:
    name: Employee-Service

  datasource:
    url: jdbc:mysql://localhost:3306/employees
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root


server:
  port: 8086